const REQUIRED = [
  "app/layout.tsx",
  "app/page.tsx",
  "app/globals.css",
  "app/not-found.tsx",
  "app/products/page.tsx",
  "app/products/[slug]/page.tsx",
  "app/about/page.tsx",
  "app/contact/page.tsx",
  "app/api/contact/route.ts",
  "app/sitemap.ts",
  "app/robots.ts",
  "content/site.ts",
  "content/products.ts",
  "package.json",
  "tsconfig.json",
  "next.config.mjs",
];